-- PUT THE DATABASE SQL TO CREATE DB AND TABLES HERE --

CREATE DATABASE flask;

CREATE TABLE User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER 'phpmyadmin'@'localhost' IDENTIFIED BY '3850';

GRANT ALL PRIVILEGES ON flask.* TO 'phpmyadmin'@'localhost';

FLUSH PRIVILEGES;



